// documentation/image-condenser-app/components/image-compressor.tsx
"use client"

import React, { useCallback, useState, useRef, useEffect } from "react"
import { Slider } from "@/components/ui/slider"
import { Download, X, ImageIcon, ChevronLeft, ChevronRight } from "lucide-react"

interface CompressedImage {
  id: string
  originalFile: File
  originalSize: number
  compressedBlob: Blob | null
  compressedSize: number
  previewUrl: string
  compressedUrl: string | null
}

function ComparisonSlider({ originalUrl, compressedUrl, originalSize, compressedSize }: {
  originalUrl: string
  compressedUrl: string
  originalSize: number
  compressedSize: number
}) {
  const [position, setPosition] = useState(50)
  const containerRef = useRef<HTMLDivElement>(null)
  const isDragging = useRef(false)

  const formatSize = (bytes: number) => {
    if (bytes === 0) return "0 B"
    const k = 1024
    const sizes = ["B", "KB", "MB"]
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return `${Number.parseFloat((bytes / k ** i).toFixed(1))} ${sizes[i]}`
  }

  const handleMove = useCallback((clientX: number) => {
    if (!containerRef.current) return
    const rect = containerRef.current.getBoundingClientRect()
    const x = clientX - rect.left
    const percentage = Math.max(0, Math.min(100, (x / rect.width) * 100))
    setPosition(percentage)
  }, [])

  const handleMouseDown = useCallback(() => {
    isDragging.current = true
  }, [])

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    if (isDragging.current) {
      handleMove(e.clientX)
    }
  }, [handleMove])

  const handleMouseUp = useCallback(() => {
    isDragging.current = false
  }, [])

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    handleMove(e.touches[0].clientX)
  }, [handleMove])

  return (
    <div
      ref={containerRef}
      className="relative aspect-video w-full cursor-ew-resize select-none overflow-hidden rounded-lg bg-muted"
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
      onTouchMove={handleTouchMove}
    >
      {/* Original Image (full, underneath) */}
      <img
        src={originalUrl || "/placeholder.svg"}
        alt="Original"
        className="absolute inset-0 h-full w-full object-contain"
        draggable={false}
      />
      
      {/* Compressed Image (clipped, on top) - using clip-path for precise reveal */}
      <img
        src={compressedUrl || "/placeholder.svg"}
        alt="Compressed"
        className="absolute inset-0 h-full w-full object-contain"
        style={{ clipPath: `inset(0 ${100 - position}% 0 0)` }}
        draggable={false}
      />

      {/* Divider Line */}
      <div
        className="absolute top-0 bottom-0 w-0.5 bg-primary shadow-lg"
        style={{ left: `${position}%`, transform: 'translateX(-50%)' }}
        onMouseDown={handleMouseDown}
        onTouchStart={handleMouseDown}
      >
        {/* Handle */}
        <div className="absolute top-1/2 left-1/2 flex h-10 w-10 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-2 border-primary bg-background shadow-lg">
          <ChevronLeft className="h-4 w-4 -mr-1 text-primary" />
          <ChevronRight className="h-4 w-4 -ml-1 text-primary" />
        </div>
      </div>

      {/* Labels */}
      <div className="absolute top-3 left-3 rounded bg-background/90 px-2 py-1 text-xs font-medium text-primary backdrop-blur-sm">
        Compressed: {formatSize(compressedSize)}
      </div>
      <div className="absolute top-3 right-3 rounded bg-background/90 px-2 py-1 text-xs font-medium text-muted-foreground backdrop-blur-sm">
        Original: {formatSize(originalSize)}
      </div>
    </div>
  )
}

function QualityIndicator({ quality, savings }: { quality: number; savings: number }) {
  const getQualityAssessment = () => {
    if (quality >= 85) {
      return {
        label: "Excellent",
        description: "Virtually no visible quality loss. Best for print or high-detail images.",
        color: "text-primary"
      }
    }
    if (quality >= 70) {
      return {
        label: "Recommended",
        description: "Optimal balance of quality and file size. Perfect for web and blogs.",
        color: "text-primary"
      }
    }
    if (quality >= 50) {
      return {
        label: "Good",
        description: "Noticeable compression on close inspection. Good for thumbnails or previews.",
        color: "text-yellow-400"
      }
    }
    return {
      label: "Aggressive",
      description: "Visible artifacts likely. Use only when file size is critical.",
      color: "text-orange-400"
    }
  }

  const assessment = getQualityAssessment()

  return (
    <div className="rounded-lg border border-border bg-card/50 p-4">
      <div className="flex items-center justify-between">
        <span className={`text-sm font-semibold ${assessment.color}`}>
          {assessment.label}
        </span>
        {savings > 0 && (
          <span className="text-sm text-muted-foreground">
            {savings}% smaller
          </span>
        )}
      </div>
      <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
        {assessment.description}
      </p>
    </div>
  )
}

export function ImageCompressor() {
  const [images, setImages] = useState<CompressedImage[]>([])
  const [quality, setQuality] = useState([75])
  const [isDragging, setIsDragging] = useState(false)
  const [isCompressing, setIsCompressing] = useState(false)
  const [selectedImageId, setSelectedImageId] = useState<string | null>(null)

  const compressImage = useCallback(
    async (file: File, compressionQuality: number): Promise<{ blob: Blob; url: string }> => {
      return new Promise((resolve, reject) => {
        const img = new Image()
        img.crossOrigin = "anonymous"

        img.onload = () => {
          const canvas = document.createElement("canvas")
          const ctx = canvas.getContext("2d")

          if (!ctx) {
            reject(new Error("Could not get canvas context"))
            return
          }

          canvas.width = img.width
          canvas.height = img.height
          ctx.drawImage(img, 0, 0)

          canvas.toBlob(
            (blob) => {
              if (blob) {
                const url = URL.createObjectURL(blob)
                resolve({ blob, url })
              } else {
                reject(new Error("Could not compress image"))
              }
            },
            "image/jpeg",
            compressionQuality / 100
          )
        }

        img.onerror = () => reject(new Error("Could not load image"))
        img.src = URL.createObjectURL(file)
      })
    },
    []
  )

  const processImages = useCallback(
    async (files: File[]) => {
      setIsCompressing(true)

      const newImages: CompressedImage[] = []

      for (const file of files) {
        if (!file.type.startsWith("image/")) continue

        const id = crypto.randomUUID()
        const previewUrl = URL.createObjectURL(file)

        try {
          const { blob, url } = await compressImage(file, quality[0])
          newImages.push({
            id,
            originalFile: file,
            originalSize: file.size,
            compressedBlob: blob,
            compressedSize: blob.size,
            previewUrl,
            compressedUrl: url,
          })
        } catch {
          newImages.push({
            id,
            originalFile: file,
            originalSize: file.size,
            compressedBlob: null,
            compressedSize: 0,
            previewUrl,
            compressedUrl: null,
          })
        }
      }

      setImages((prev) => [...prev, ...newImages])
      if (newImages.length > 0 && !selectedImageId) {
        setSelectedImageId(newImages[0].id)
      }
      setIsCompressing(false)
    },
    [compressImage, quality, selectedImageId]
  )

  const recompressAll = useCallback(async () => {
    if (images.length === 0) return

    setIsCompressing(true)

    const recompressed = await Promise.all(
      images.map(async (img) => {
        try {
          if (img.compressedUrl) {
            URL.revokeObjectURL(img.compressedUrl)
          }
          const { blob, url } = await compressImage(img.originalFile, quality[0])
          return {
            ...img,
            compressedBlob: blob,
            compressedSize: blob.size,
            compressedUrl: url,
          }
        } catch {
          return img
        }
      })
    )

    setImages(recompressed)
    setIsCompressing(false)
  }, [images, compressImage, quality])

  // Real-time recompression when quality changes (debounced)
  const qualityRef = useRef(quality[0])
  const debounceTimerRef = useRef<NodeJS.Timeout | null>(null)
  const imagesRef = useRef(images)
  
  // Keep imagesRef in sync
  useEffect(() => {
    imagesRef.current = images
  }, [images])

  useEffect(() => {
    // Skip if quality hasn't actually changed or no images
    if (qualityRef.current === quality[0]) {
      return
    }
    
    if (imagesRef.current.length === 0) {
      qualityRef.current = quality[0]
      return
    }
    
    console.log("[v0] Quality changed from", qualityRef.current, "to", quality[0])
    qualityRef.current = quality[0]

    // Clear any pending recompression
    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current)
    }

    // Debounce recompression for 150ms to allow smooth slider interaction
    debounceTimerRef.current = setTimeout(async () => {
      console.log("[v0] Starting recompression at quality:", quality[0])
      setIsCompressing(true)

      const currentImages = imagesRef.current
      const recompressed = await Promise.all(
        currentImages.map(async (img) => {
          try {
            if (img.compressedUrl) {
              URL.revokeObjectURL(img.compressedUrl)
            }
            const { blob, url } = await compressImage(img.originalFile, quality[0])
            console.log("[v0] Recompressed", img.originalFile.name, "new size:", blob.size)
            return {
              ...img,
              compressedBlob: blob,
              compressedSize: blob.size,
              compressedUrl: url,
            }
          } catch {
            return img
          }
        })
      )

      setImages(recompressed)
      setIsCompressing(false)
      console.log("[v0] Recompression complete")
    }, 150)

    return () => {
      if (debounceTimerRef.current) {
        clearTimeout(debounceTimerRef.current)
      }
    }
  }, [quality, compressImage])

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault()
      setIsDragging(false)

      const files = Array.from(e.dataTransfer.files).filter((f) =>
        f.type.startsWith("image/")
      )
      if (files.length > 0) {
        processImages(files)
      }
    },
    [processImages]
  )

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }, [])

  const handleFileSelect = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const files = e.target.files
      if (files) {
        processImages(Array.from(files))
      }
      e.target.value = ""
    },
    [processImages]
  )

  const removeImage = useCallback((id: string) => {
    setImages((prev) => {
      const img = prev.find((i) => i.id === id)
      if (img) {
        URL.revokeObjectURL(img.previewUrl)
        if (img.compressedUrl) URL.revokeObjectURL(img.compressedUrl)
      }
      const filtered = prev.filter((i) => i.id !== id)
      if (selectedImageId === id) {
        setSelectedImageId(filtered[0]?.id || null)
      }
      return filtered
    })
  }, [selectedImageId])

  const clearAll = useCallback(() => {
    for (const img of images) {
      URL.revokeObjectURL(img.previewUrl)
      if (img.compressedUrl) URL.revokeObjectURL(img.compressedUrl)
    }
    setImages([])
    setSelectedImageId(null)
  }, [images])

  const downloadImage = useCallback((img: CompressedImage) => {
    if (!img.compressedUrl || !img.compressedBlob) return

    const link = document.createElement("a")
    const originalName = img.originalFile.name
    const baseName = originalName.substring(0, originalName.lastIndexOf(".")) || originalName
    link.download = `${baseName}-squished.jpg`
    link.href = img.compressedUrl
    link.click()
  }, [])

  const downloadAll = useCallback(() => {
    for (const img of images) {
      if (img.compressedUrl && img.compressedBlob) {
        downloadImage(img)
      }
    }
  }, [images, downloadImage])

  const formatSize = (bytes: number) => {
    if (bytes === 0) return "0 B"
    const k = 1024
    const sizes = ["B", "KB", "MB"]
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return `${Number.parseFloat((bytes / k ** i).toFixed(1))} ${sizes[i]}`
  }

  const getSavings = (original: number, compressed: number) => {
    if (original === 0) return 0
    return Math.round(((original - compressed) / original) * 100)
  }

  const totalOriginal = images.reduce((acc, img) => acc + img.originalSize, 0)
  const totalCompressed = images.reduce((acc, img) => acc + img.compressedSize, 0)
  const totalSavings = getSavings(totalOriginal, totalCompressed)
  
  const selectedImage = images.find(img => img.id === selectedImageId)

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10">
          <h1 className="text-4xl font-black tracking-tighter text-foreground sm:text-5xl">
            Squish
          </h1>
          <span className="hidden text-sm tracking-wide text-muted-foreground sm:block">
            Image compression for writers
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-6 py-12 lg:px-10 lg:py-16">
        {/* Intro Section */}
        <div className="mb-16 max-w-xl">
          <p className="text-xl leading-relaxed text-muted-foreground">
            Drop your images below to compress them instantly. Drag the slider on the preview 
            to compare original and compressed versions side by side.
          </p>
        </div>

        <div className="grid gap-16 xl:grid-cols-[1fr,400px]">
          {/* Left Column */}
          <div className="space-y-10">
            {/* Drop Zone */}
            <div
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              className={`relative flex min-h-[200px] cursor-pointer flex-col items-center justify-center rounded border-2 border-dashed transition-all duration-200 ${
                isDragging
                  ? "border-primary bg-primary/5"
                  : "border-border hover:border-muted-foreground"
              }`}
            >
              <input
                type="file"
                accept="image/png,image/jpeg,image/jpg"
                multiple
                onChange={handleFileSelect}
                className="absolute inset-0 cursor-pointer opacity-0"
                aria-label="Select images to compress"
              />
              <div className="flex flex-col items-center gap-4 px-8 text-center">
                <ImageIcon className={`h-8 w-8 transition-colors ${isDragging ? "text-primary" : "text-muted-foreground"}`} />
                <div>
                  <p className={`text-lg font-medium transition-colors ${isDragging ? "text-primary" : "text-foreground"}`}>
                    {isDragging ? "Release to squish" : "Drop images here"}
                  </p>
                  <p className="mt-1 text-sm text-muted-foreground">
                    or click to browse — PNG and JPG supported
                  </p>
                </div>
              </div>
            </div>

            {/* Comparison Preview */}
            {selectedImage && selectedImage.compressedUrl && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-semibold text-foreground">Preview Comparison</h2>
                  <p className="text-sm text-muted-foreground">Drag slider to compare</p>
                </div>
                <ComparisonSlider
                  originalUrl={selectedImage.previewUrl}
                  compressedUrl={selectedImage.compressedUrl}
                  originalSize={selectedImage.originalSize}
                  compressedSize={selectedImage.compressedSize}
                />
              </div>
            )}

            {/* Image Thumbnails */}
            {images.length > 0 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-semibold text-foreground">
                    {images.length} {images.length === 1 ? "image" : "images"}
                  </h2>
                  <button
                    type="button"
                    onClick={clearAll}
                    className="text-sm text-muted-foreground transition-colors hover:text-foreground"
                  >
                    Clear all
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
                  {images.map((img) => {
                    const savings = getSavings(img.originalSize, img.compressedSize)
                    const isSelected = selectedImageId === img.id
                    return (
                      <div
                        key={img.id}
                        className={`group relative cursor-pointer overflow-hidden rounded border-2 transition-all ${
                          isSelected ? "border-primary" : "border-transparent hover:border-muted-foreground"
                        }`}
                        onClick={() => setSelectedImageId(img.id)}
                        onKeyDown={(e) => e.key === 'Enter' && setSelectedImageId(img.id)}
                        role="button"
                        tabIndex={0}
                      >
                        <div className="aspect-square bg-muted">
                          <img
                            src={img.compressedUrl || img.previewUrl}
                            alt={img.originalFile.name}
                            className="h-full w-full object-cover"
                          />
                        </div>
                        
                        {/* Savings Badge */}
                        {savings > 0 && (
                          <div className="absolute top-2 left-2 rounded bg-primary px-1.5 py-0.5 text-xs font-bold text-primary-foreground">
                            -{savings}%
                          </div>
                        )}

                        {/* Hover Actions */}
                        <div className="absolute inset-0 flex items-center justify-center gap-1 bg-background/80 opacity-0 transition-opacity group-hover:opacity-100">
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation()
                              downloadImage(img)
                            }}
                            disabled={!img.compressedBlob}
                            className="rounded p-2 text-foreground transition-colors hover:bg-muted"
                            aria-label="Download"
                          >
                            <Download className="h-5 w-5" />
                          </button>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation()
                              removeImage(img.id)
                            }}
                            className="rounded p-2 text-foreground transition-colors hover:bg-muted"
                            aria-label="Remove"
                          >
                            <X className="h-5 w-5" />
                          </button>
                        </div>

                        {/* File info */}
                        <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-background/90 to-transparent p-2 pt-6">
                          <p className="truncate text-xs text-foreground">
                            {formatSize(img.compressedSize)}
                          </p>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            )}
          </div>

          {/* Right Column - Controls */}
          <div className="space-y-8">
            {/* Quality Control */}
            <div className="space-y-6 rounded border border-border bg-card p-6">
              <div className="flex items-baseline justify-between">
                <h3 className="text-sm font-medium uppercase tracking-widest text-muted-foreground">
                  Quality
                </h3>
                <span className="text-4xl font-black tabular-nums text-primary">
                  {quality[0]}%
                </span>
              </div>
              
              <Slider
                value={quality}
                onValueChange={setQuality}
                min={10}
                max={100}
                step={5}
                className="w-full"
              />
              
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>Smaller file</span>
                <span>Better quality</span>
              </div>

              <QualityIndicator 
                quality={quality[0]} 
                savings={totalSavings}
              />
            </div>

            {/* Stats */}
            {images.length > 0 && (
              <div className="space-y-6 rounded border border-border bg-card p-6">
                <h3 className="text-sm font-medium uppercase tracking-widest text-muted-foreground">
                  Summary
                </h3>
                
                <div className="space-y-4">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Original</span>
                    <span className="font-medium text-foreground">{formatSize(totalOriginal)}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Compressed</span>
                    <span className="font-medium text-foreground">{formatSize(totalCompressed)}</span>
                  </div>
                  <div className="border-t border-border pt-4">
                    <div className="flex items-baseline justify-between">
                      <span className="text-sm text-muted-foreground">Saved</span>
                      <div className="text-right">
                        <span className="text-3xl font-black text-primary">
                          {totalSavings}%
                        </span>
                        <p className="text-sm text-muted-foreground">
                          {formatSize(totalOriginal - totalCompressed)}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={downloadAll}
                  className="flex w-full items-center justify-center gap-2 rounded bg-primary px-4 py-3 font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
                >
                  <Download className="h-5 w-5" />
                  Download all
                </button>
              </div>
            )}

            {/* Loading */}
            {isCompressing && (
              <div className="flex items-center justify-center gap-3 rounded border border-border bg-card p-4">
                <div className="h-5 w-5 animate-spin rounded-full border-2 border-muted-foreground/30 border-t-primary" />
                <span className="text-sm text-muted-foreground">Compressing...</span>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="mt-16 border-t border-border">
        <div className="mx-auto max-w-7xl px-6 py-8 lg:px-10">
          <p className="text-sm text-muted-foreground">
            All processing happens locally in your browser. Your images never leave your device.
          </p>
        </div>
      </footer>
    </div>
  )
}

// app/components/ImageCompressor.vue
<template>
  <div class="min-h-screen bg-background">
    <header class="border-b border-border">
      <div class="mx-auto flex h-24 max-w-[2000px] items-center justify-between px-6 pb-6 lg:px-10">
        <h1 class="text-5xl font-black tracking-tighter text-foreground sm:text-6xl lg:text-7xl">
          Squish
        </h1>
        <span class="hidden text-sm tracking-wide text-muted-foreground sm:block">image compression for writers and designers</span>
      </div>
    </header>
    <main class="mx-auto max-w-[2000px] px-6 py-12 lg:px-10 lg:py-16">
      <div class="mb-16 max-w-xl">
        <p class="text-xl leading-relaxed text-muted-foreground">
          Drop your images below to compress them instantly. Drag the slider on the preview to compare original and compressed versions side by side.
        </p>
      </div>
      <div class="grid gap-10 xl:grid-cols-[1fr_360px]">
        <div class="space-y-10">
          <div
            :class="['relative flex min-h-[200px] cursor-pointer flex-col items-center justify-center rounded border-2 border-dashed transition-all duration-200', isDragging ? 'border-primary bg-primary/5' : 'border-border hover:border-muted-foreground']"
            @drop="handleDrop"
            @dragover="handleDragOver"
            @dragleave="handleDragLeave"
          >
            <input
              type="file"
              accept="image/png,image/jpeg,image/jpg"
              multiple
              class="absolute inset-0 cursor-pointer opacity-0"
              aria-label="Select images to compress"
              @change="handleFileSelect"
            >
            <div class="flex flex-col items-center gap-4 px-8 text-center">
              <UIcon
                name="i-lucide-image"
                :class="['h-8 w-8 transition-colors', isDragging ? 'text-primary' : 'text-muted-foreground']"
              />
              <div>
                <p :class="['text-lg font-medium transition-colors', isDragging ? 'text-primary' : 'text-foreground']">
                  {{ isDragging ? 'Release to squish' : 'Drop images here' }}
                </p>
                <p class="mt-1 text-sm text-muted-foreground">
                  or click to browse — PNG and JPG supported
                </p>
              </div>
            </div>
          </div>
          <div
            v-if="selectedImage && selectedImage.compressedUrl"
            class="space-y-4"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2">
                <h2 class="text-lg font-semibold text-foreground">
                  Preview Comparison
                </h2>
                <span class="text-sm text-muted-foreground">Drag slider to compare</span>
              </div>
              <button
                class="text-sm text-primary transition-colors hover:text-primary/80"
                @click="downloadImage(selectedImage)"
              >
                Download this image
              </button>
            </div>
            <ComparisonSlider
              :key="`${selectedImage.id}-${selectedImage.compressedUrl}`"
              :original-url="selectedImage.previewUrl"
              :compressed-url="selectedImage.compressedUrl"
              :original-size="selectedImage.originalSize"
              :compressed-size="selectedImage.compressedSize"
            />
          </div>
          <div
            v-if="images.length > 0"
            class="space-y-4"
          >
            <div class="flex items-center justify-between">
              <h2 class="text-lg font-semibold text-foreground">
                {{ images.length }} {{ images.length === 1 ? 'image' : 'images' }}
              </h2>
              <button
                class="text-sm text-muted-foreground transition-colors hover:text-foreground"
                @click="clearAll"
              >
                Clear all
              </button>
            </div>
            <div class="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
              <div
                v-for="img in images"
                :key="img.id"
                :class="['group relative cursor-pointer overflow-hidden rounded border-2 transition-all', selectedImageId === img.id ? 'border-primary' : 'border-transparent hover:border-muted-foreground']"
                role="button"
                tabindex="0"
                @click="selectedImageId = img.id"
              >
                <div class="aspect-square bg-muted">
                  <img
                    :src="img.previewUrl"
                    :alt="img.originalFile.name"
                    class="h-full w-full object-cover"
                  >
                </div>
                <div
                  v-if="getSavings(img.originalSize, img.compressedSize) > 0"
                  class="absolute top-2 left-2 rounded bg-primary px-1.5 py-0.5 text-xs font-bold text-primary-foreground"
                >
                  -{{ getSavings(img.originalSize, img.compressedSize) }}%
                </div>
                <div class="absolute inset-0 flex items-center justify-center gap-2 bg-background/80 opacity-0 transition-opacity group-hover:opacity-100">
                  <button
                    class="rounded-full bg-primary p-2 text-primary-foreground transition-colors hover:bg-primary/90"
                    aria-label="Download"
                    @click.stop="downloadImage(img)"
                  >
                    <UIcon
                      name="i-lucide-download"
                      class="h-5 w-5"
                    />
                  </button>
                  <button
                    class="rounded-full bg-destructive p-2 text-destructive-foreground transition-colors hover:bg-destructive/90"
                    aria-label="Remove"
                    @click.stop="removeImage(img.id)"
                  >
                    <UIcon
                      name="i-lucide-x"
                      class="h-5 w-5"
                    />
                  </button>
                </div>
                <div class="absolute inset-x-0 bottom-0 bg-linear-to-t from-background/90 to-transparent p-2 pt-6">
                  <p class="truncate text-xs text-foreground">
                    {{ formatSize(img.compressedSize) }}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="space-y-8">
          <div class="space-y-6 rounded border border-border bg-card p-6">
            <div class="flex items-baseline justify-between">
              <h3 class="text-sm font-medium uppercase tracking-widest text-muted-foreground">
                Quality
              </h3>
              <span class="text-4xl font-black tabular-nums text-primary">{{ quality }}%</span>
            </div>
            <USlider
              v-model="quality"
              :min="10"
              :max="100"
              :step="5"
              color="primary"
              size="lg"
              class="w-full"
            />
            <div class="flex justify-between text-xs text-muted-foreground">
              <span>Smaller file</span>
              <span>Better quality</span>
            </div>
            <QualityIndicator
              :quality="quality"
              :savings="totalSavings"
            />
          </div>
          <div
            v-if="images.length > 0"
            class="space-y-6 rounded border border-border bg-card p-6"
          >
            <h3 class="text-sm font-medium uppercase tracking-widest text-muted-foreground">
              Summary
            </h3>
            <div class="space-y-4">
              <div class="flex justify-between">
                <span class="text-muted-foreground">Original</span>
                <span class="font-mono text-foreground">{{ formatSize(totalOriginalSize) }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Compressed</span>
                <span class="font-mono text-foreground">{{ formatSize(totalCompressedSize) }}</span>
              </div>
              <div class="border-t border-border pt-4">
                <div class="flex justify-between items-start">
                  <span class="font-medium text-foreground">Saved</span>
                  <div class="flex flex-col items-end gap-1">
                    <span class="font-mono text-2xl font-bold text-primary">{{ totalSavings }}%</span>
                    <span class="font-mono text-sm text-foreground">{{ formatSize(totalOriginalSize - totalCompressedSize) }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            v-if="images.length > 1"
            class="space-y-4"
          >
            <button
              class="flex w-full items-center justify-center gap-2 rounded bg-primary px-4 py-3 font-medium text-primary-foreground transition-colors hover:bg-primary/90"
              @click="downloadAll"
            >
              <UIcon
                name="i-lucide-download"
                class="h-5 w-5"
              />Download all
            </button>
          </div>
          <div
            v-if="isCompressing"
            class="flex items-center justify-center gap-3 rounded border border-border bg-card p-4"
          >
            <div class="h-5 w-5 animate-spin rounded-full border-2 border-muted-foreground/30 border-t-primary" />
            <span class="text-sm text-muted-foreground">Compressing...</span>
          </div>
        </div>
      </div>
    </main>
    <footer class="mt-16 border-t border-border">
      <div class="mx-auto max-w-[2000px] px-6 py-8 lg:px-10">
        <div class="flex flex-col items-center gap-4 text-center">
          <p class="text-lg font-semibold tracking-wide" style="color: #45d87a;">
            Privacy-focused • Real-time preview • Instant compression
          </p>
          <p class="text-sm text-muted-foreground">
            All processing happens locally in your browser. Your images never leave your device.
          </p>
        </div>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import type { CompressedImage } from '~/composables/useImageCompression'

const { compressImage, formatSize, getSavings } = useImageCompression()

const images = ref<CompressedImage[]>([])
const quality = ref(75)
const isDragging = ref(false)
const selectedImageId = ref<string | null>(null)
const isCompressing = ref(false)

let debounceTimer: ReturnType<typeof setTimeout> | null = null

const selectedImage = computed(() => images.value.find(img => img.id === selectedImageId.value) || null)
const totalOriginalSize = computed(() => images.value.reduce((sum, img) => sum + img.originalSize, 0))
const totalCompressedSize = computed(() => images.value.reduce((sum, img) => sum + img.compressedSize, 0))
const totalSavings = computed(() => getSavings(totalOriginalSize.value, totalCompressedSize.value))

const handleDragOver = (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = true
}

const handleDragLeave = () => {
  isDragging.value = false
}

const handleDrop = async (e: DragEvent) => {
  e.preventDefault()
  isDragging.value = false
  const files = Array.from(e.dataTransfer?.files || []).filter(f => f.type.startsWith('image/'))
  if (files.length > 0) await processFiles(files)
}

const handleFileSelect = async (e: Event) => {
  const input = e.target as HTMLInputElement
  const files = Array.from(input.files || [])
  if (files.length > 0) await processFiles(files)
  input.value = ''
}

const processFiles = async (files: File[]) => {
  isCompressing.value = true
  for (const file of files) {
    const id = crypto.randomUUID()
    const previewUrl = URL.createObjectURL(file)
    const newImage: CompressedImage = { id, originalFile: file, originalSize: file.size, compressedBlob: null, compressedSize: file.size, previewUrl, compressedUrl: null }
    images.value.push(newImage)
    if (!selectedImageId.value) selectedImageId.value = id
    try {
      const { blob, url } = await compressImage(file, quality.value)
      const idx = images.value.findIndex(img => img.id === id)
      if (idx !== -1) { images.value[idx].compressedBlob = blob; images.value[idx].compressedSize = blob.size; images.value[idx].compressedUrl = url }
    }
    catch (error) { console.error('Compression failed:', error) }
  }
  isCompressing.value = false
}

const recompressAll = async () => {
  isCompressing.value = true
  for (const img of images.value) {
    if (img.compressedUrl) URL.revokeObjectURL(img.compressedUrl)
    try {
      const { blob, url } = await compressImage(img.originalFile, quality.value)
      img.compressedBlob = blob; img.compressedSize = blob.size; img.compressedUrl = url
    }
    catch (error) { console.error('Recompression failed:', error) }
  }
  isCompressing.value = false
}

const downloadImage = (img: CompressedImage) => {
  if (!img.compressedBlob) return
  const a = document.createElement('a')
  a.href = URL.createObjectURL(img.compressedBlob)
  a.download = img.originalFile.name.replace(/\.[^.]+$/, '') + '_compressed.jpg'
  a.click()
  URL.revokeObjectURL(a.href)
}

const downloadAll = async () => {
  for (const img of images.value) { if (img.compressedBlob) downloadImage(img) }
}

const removeImage = (id: string) => {
  const img = images.value.find(i => i.id === id)
  if (img) { URL.revokeObjectURL(img.previewUrl); if (img.compressedUrl) URL.revokeObjectURL(img.compressedUrl) }
  images.value = images.value.filter(i => i.id !== id)
  if (selectedImageId.value === id) selectedImageId.value = images.value[0]?.id || null
}

const clearAll = () => {
  images.value.forEach((img) => { URL.revokeObjectURL(img.previewUrl); if (img.compressedUrl) URL.revokeObjectURL(img.compressedUrl) })
  images.value = []; selectedImageId.value = null
}

watch(quality, async () => {
  if (images.value.length === 0) return
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(async () => {
    await recompressAll()
  }, 150)
}, { immediate: false })

onUnmounted(() => {
  images.value.forEach((img) => { URL.revokeObjectURL(img.previewUrl); if (img.compressedUrl) URL.revokeObjectURL(img.compressedUrl) })
  if (debounceTimer) clearTimeout(debounceTimer)
})
</script>
